name: Integração Contínua

on: 
  pull_request:
    branches:
      - main

  push:

jobs:
  executa_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout # Clona o repositório para a máquina do workflow
        uses: actions/checkout@v2
      
      - name: Instala o Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip

      - name: Install requirements dependencies
        run: python -m pip install -r requirements.txt

      #- name: Executa o Black
      #  run: python -m black app.py

      #- name: Executa o isort
      #  run: python -m isort app.py --check

      #- name: Executa o pydocstyle
      #  run: python -m pydocstyle app.py

      - name: Executa os testes unitários
        run: python -m pytest
      
